### PR TITLE
Added CookieOrder and APLine FRQs

### PR DESCRIPTION
**Pull request by aunyks**
I have added Questions 1 and 2 from the 2010 Free Response Packet. Sorry for so many commits. Git kept deleting files or adding random text to files so I had to keep fixing those.

### CODE REVIEW

**Comment by ericsonga** [comment]
There are conflicts with the current version.  Resolve the conflicts first.

**Comment by ericsonga** [comment]
The conflicts are what you talked about as "random" text in your commit.

**Comment by gnash48** [comment]
After checking the "Files Changed" tab on Github it seems that it's saying that index.rst from my fork is conflicting with the one on yours. But I looked closely at the diff and noticed that the text editor had deleted and then re-added lines to the file. So, in the end there would be no problem with the merge.

**Comment by gnash48** [comment]
But, I can redo the pull request if you'd like.

**Comment by ericsonga** [comment]
I am still getting that this banch has conflicts that must be resolved.

**Comment by ericsonga** [comment]
I fixed the problem in index.rst and did a pull request into the master with your changes.  You might want to delete this branch and create a new branch from the master now.

**Comment by aunyks** [comment]
Okay. Glad you were able to fix it. I'll delete my branch and reclone from yours

**Pull request closed without merging**
